### ISSUE TITLE
Update bootstrapping guide for acceptance

### ISSUE THREAD

**Issue by steverfrancis** [talos-systems/sidero#177]
https://www.sidero.dev/docs/v0.1/configuration/servers/#server-acceptance talks about the criticality of server acceptance.  (it would be clearer if it said "accepted: must be set to true" on that page - I thought acceptance was a process that needed to occur, not a config.)

But the bootstrapping guide https://www.sidero.dev/docs/v0.1/guides/bootstrapping/ doesn't mention acceptance.
It talks about registering servers - which led me to wonder are all registered servers accepted?

The answer is You can set it up to automatically accept any new server, but the process should generally be:  machine boots, gets registered into Sidero.  Then, some business process determines whether that server should be "accepted" as a valid server into Sidero.  A registered server is "known" to Sidero (registered with machine info), but it will not be manipulated in any way until it is "accepted"

So the bootstrapping guide needs to cover accepting the servers.

So in this Issue:
- update /configuration/servers to say that accepted:true must be set
- update /guides/bootstrapping/ to detail how to accept servers, and the concept of doing so
- update Concepts page to define "accepted", "allocated", "clean" states.

What is effect if an "Accepted" server is later modified to "Accepted:false"? Is it de-provisioned? Wiped? Or just frozen in its current state? How about if its currently allocated? DOes that change it? Document that in concepts too, I think.

**Comment by Ulexus** [comment]
I think it would be good to _have_ a process (API) by which you can accept a server, but it still ultimately does the same thing: set the `Server`'s `accepted` flag.  Moreover, I agree that this needs general expansion, to explain the what and why of acceptance and general flow of machines in Sidero.

**Comment by Ulexus** [comment]
We still need an additional doc for lifecycle management, I think, including things like how to take a `Server` out of commission, which would address your second point.

**Comment by steverfrancis** [comment]
The servers doc is good, but the Bootstrapping guide doesn't mention acceptance, and still says 
"At this point, any servers on the same network as Sidero should PXE boot using the Sidero PXE service. To register a server with Sidero, simply turn it on and Sidero will do the rest."
I dont think (?) that is true...

We want people to be ableto follow a simple guide in one doc without a lot of cross referencing...

**Comment by steverfrancis** [comment]
Also I'dlike to see the Servers page talk about 
 "accepted", "allocated", "clean" states.

**Comment by steverfrancis** [comment]
Also update https://www.sidero.dev/docs/v0.1/guides/first-cluster/#register-the-servers
