### ISSUE TITLE
Sidero should construct custom iPXE images

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/sidero#227]
Sidero should construct custom iPXE images for each environment, referencing Sidero's metadata server URL.  This eliminates the loop problem of bootstrapping iPXE and then loading the iPXE config without resorting to class distinctions from the DHCP server, making Sidero much easier to implement on more networks.

See the iPXE chainloading [page](https://ipxe.org/howto/chainloading), Breaking the Infinite Loop with an embedded script section.

Note that the EMBED mechanism works for both undionly.kpxe (BIOS) and ipxe.efi (EFI) iPXE bootstraps (even though the documentation does not say so).

It is further suggested that Sidero may accept user-supplied versions, which may have additional site-specific information.  This kind of override could, perhaps, be supplied in a Secret  (Sidero generates a default one or uses one, if it already exists).

Secrets/ConfigMaps would be the natural place to store these generated binary blobs, since metadata information could be added, and they could easily be overridden.  However, the default ipxe.efi image is perilously close to the 1MB limit, so it seems the use of a Volume (default local) is the only reasonable option.  It is worth noting, however, that this file does compress very well.  I show better than 50% compression with `gzip -9`.

So the idea would be to store in a Volume something like:

```
/environment/cluster-name-0/amd64/ipxe.efi
/environment/cluster-name-0/amd64/undionly.ipxe
/environment/cluster-name-0/amd64/url-hash.undionly.ipxe.md5
/environment/cluster-name-0/amd64/url-hash.ipxe.efi.md5
/environment/cluster-name-0/aarch64/ipxe.efi
/environment/cluster-name-0/aarch64/url-hash.ipxe.efi.md5
```

Th url-hash.md5 files are arbitrarily-named, but are to quickly determine whether the existing binaries were built against the same Sidero metadata URL as what it "currently" the case (thus indicating whether they need to be rebuilt).  Some other scheme is perfectly fine.

## building

In general, the configuration consists of a file named, say, `talos.ipxe`, put in the `src/` directory of the ipxe [source tree](https://ipxe.org/download).  This file would have the format of something like:

```
#!ipxe
dhcp
chain http://sidero.ip.address:8081/boot.ipxe
```

Then, the images are built:
```sh
make bin-x86_64-efi/ipxe.efi EMBED=talos.ipxe
make bin/undionly.kpxe EMBED=talos.ipxe
```

These builds should be able to be spawned by Jobs, so they can have their own short-lived build containers.

**Comment by bzub** [comment]
I've got a basic implementation of the ipxe builder job. Only uses configmaps at the time of this comment. Could be enhanced for this purpose. https://github.com/bzub/kube-dnsmasq/tree/main/build-ipxe
