### ISSUE TITLE
httpboot support

### ISSUE THREAD

**Issue by smira** [talos-systems/sidero#241]
it is newer and more reliable  way to fetch ipxe rom than udp based tftp 

example config:

```
class "pxeclients"{
      match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
      next-server 192.168.111.1;
      filename "/bootx64.efi";
    }
    class "httpclients" {
      match if substring (option vendor-class-identifier, 0, 10) = "HTTPClient";
      option vendor-class-identifier "HTTPClient";
      filename "http://www.httpboot.local/sle/EFI/BOOT/bootx64.efi";
    }
```

probably all we need is to serve same files over http://

**Comment by andrewrynhard** [comment]
@Unix4ever I think this was closed by accident?

**Comment by Unix4ever** [comment]
nope, we already have http boot working actually.

**Comment by Unix4ever** [comment]
I should have left a comment there. But after looking through the code with Andrey, we found out that we already serve assets from `/env`:
https://github.com/talos-systems/sidero/blob/master/app/metal-controller-manager/internal/ipxe/ipxe_server.go#L161

And the way ipxe works it will fetch the file from the same host if the syntax like this is used:

**Comment by smira** [comment]
To be more precise, we use TFTP only to deliver `ipxe.efi` to the network cards which don't have `iPXE` burned into their EEPROM, and after getting to `iPXE` stage, all the assets are always downloaded by HTTP.

We can't get rid of TFTP to support legacy PXE ROMs on network cards. If network card has iPXE built in, it goes over http always.

**Comment by andrewrynhard** [comment]
And what about the efi portion of this ticket?

**Comment by andrewrynhard** [comment]
I guess that is what ipxe.efi is.

**Comment by Unix4ever** [comment]
yeah... I guess we can't get rid of TFTP in that case.

**Comment by smira** [comment]
oh, I think I understand what this ticket is about really 

@Unix4ever I think what we need to do then is to support serving assets from tftp directory from http iPXE server

**Comment by smira** [comment]
that is even easier, we just need to make sure we can do `http://IP:8081/ipxe.efi` to load iPXE from UEFI systems over HTTP, not over TFTP

**Comment by Unix4ever** [comment]
ok, shouldn't be hard to change I guess.

**Comment by andrewrynhard** [comment]
I'm confused on the diff between iPXE class and HTTPBoot class.

**Comment by smira** [comment]
I guess this is it: https://ipxe.org/appnote/uefihttp

**Comment by smira** [comment]
From Sidero point of view, it is to expose tftp assets over http, everything else is anyways on DHCP server side.

So that `http://:8081/tftp` maps to `/var/lib/sidero/tftp`
