### ISSUE TITLE
serial console setting does not work with --extra-agent-kernel-args

### ISSUE THREAD

**Issue by abckey** [talos-systems/sidero#251]
By default, agent environment kernel parameters has `console=ttyS0`.
With newly added `--extra-agent-kernel-args`, enabled the ability to add  `console=ttyS1`. (the config working in my servers)
The implemenation ended up with both parameters present, I'm not sure how kernel handles this, but in real test, I still could not get serial console output during agent running.

From from https://www.kernel.org/doc/html/v5.9/admin-guide/serial-console.html, below is mentioned:

    Note that you can only define one console per device type (serial, video).

**Comment by smira** [comment]
I will look into overriding defaults

**Comment by smira** [comment]
@abckey you can try updated version from #252 by updating image reference for `sidero-controller-manager` to `ghcr.io/smira/metal-controller-manager:v0.1.0-alpha.12-13-g51f488f`

**Comment by abckey** [comment]
with the test image, `--extra-agent-kernel-args=console=ttyS1,115200` ended up in kernel cmdline as `console=ttyS1 console=tty0 console=ttyS0`, did I set it in right format or still a bit fix to do?

**Comment by andrewrynhard** [comment]
> with the test image, `--extra-agent-kernel-args=console=ttyS1,115200` ended up in kernel cmdline as `console=ttyS1 console=tty0 console=ttyS0`, did I set it in right format or still a bit fix to do?

`--extra-agent-kernel-args=console="ttyS1,115200"`

**Comment by smira** [comment]
I believe 115200 should be default, so you can skip it. @abckey does it fix the console for you?

**Comment by abckey** [comment]
It seems 9600 is the default,it works only with my old HP servers, my newer servers need 115200 to work.
tested ` --extra-agent-kernel-args=console="ttyS1,115200"`,  it generates `console="ttyS1 console=tty0 console=ttyS0` , so still something needs to be done to get it properly set ?

**Comment by smira** [comment]
@abckey I'll do more testing today and I will get back to you

**Comment by smira** [comment]
@abckey I have a new image `ghcr.io/smira/metal-controller-manager:v0.1.0-alpha.12-13-g4dba68a`

This changes format for `--extra-agent-kernel-args` to better handle kernel args, it now accepts args in the format of kernel command line:

```
      - args:
        ...
        - --extra-agent-kernel-args
        - panic=5 console=ttyS0
```

(just use spaces to separate different options)

**Comment by abckey** [comment]
@smira it works now as expected.
from:
```
- --extra-agent-kernel-args
- console=tty0 console=ttyS1,115200
```
I got in kernal cmdline:
```
console=tty0 console=ttyS1,115200
```

**Comment by smira** [comment]
Thanks, we'll get into the next release
