### ISSUE TITLE
Publish ARM images

### ISSUE THREAD

**Issue by DWSR** [talos-systems/sidero#304]
Currently, all the Sidero images are published for `amd64` only, which makes my RPi cluster very sad.

**Comment by smira** [comment]
I really like the idea, it's too late for 0.2, but might be nice feature for 0.3

As part of that I would also refactor the build as well

**Comment by smira** [comment]
we have this implemented partially in 0.3 now, there might be some third-party images which still need to be fixed to be multi-arch, but the core of Sidero should be multi-arch in `master`

**Comment by smira** [comment]
needs final validation once #390 is done

**Comment by smira** [comment]
Verified that Sidero works properly on Raspberry PI. Sidero can provision amd64 nodes, it won't be able to provision other RPIs out of the box as we don't have iPXE for RPi (but we have arm64 UEFI iPXE). 

This feature will be available as part of next 0.3 release. 

The only caveat is that CAPI itself is using outdated `kube-rbac-proxy` image which doesn't support `arm64`, so easy workaround is to patch the Deployment bumping `kube-rbac-proxy` version from `v0.4.1` to `v0.8.0`.

**Comment by BobyMCbobs** [comment]
Also here seeking arm64 support.
Looking to network boot Talos onto RPis using CAPI+Sidero.
