### ISSUE TITLE
Add a Sidero globals ConfigMap

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/sidero#312]
There are a few global settings which could be usefully used by Sidero, such as:
 - Self-reference URI (endpoint name (HTTP URL) for itself)
 - BIOS vs EFI boot (though it should be overridable on a per-Server basis), such as for IPMI netboot reboot commands (#274)
 - EOF or 404 (#287)

Make sure this is tagged and constructed with survivability in mind (such as for clusterctl upgrades and moves)

**Comment by smira** [comment]
Configuration was added via `clusterctl` variables or environment variables (this is what `clusterctl` supports), and if set properly settings survive upgrades. 

Other issues linked here need to be implemented separately.
