### ISSUE TITLE
validate reconciliation loops

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/sidero#315]
It appears there are a number of scenarios in which machine configs (at least) are not regenerated when constituent items (Servers, ServerClasses, etc) are updated.  We should test these (and add to automated testing scenarios).

**Comment by smira** [comment]
@Ulexus any specific examples of bugs we have? I don't know any at the moment

**Comment by Ulexus** [comment]
Unfortunately, I don't remember exactly.  As I recall, there were some issues with machine configs not being regenerated when configpatches were changed on upstream resources (like ServerClasses)

**Comment by smira** [comment]
Machine configuration is not persisted anywhere iirc, so it doesn't need to be reconciled. Talos fetches machine config only once though, so in some sense changes to config patches don't apply to already provisioned nodes.

**Comment by Ulexus** [comment]
In that case, we should probably just close this issue until we have a clear, describable problem.
