### ISSUE TITLE
Environment no longer needs talos.config

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/sidero#460]
We create an environment with the `talos.config` arg. This is inject automatically now. We should remove it.

**Comment by andrewrynhard** [comment]
Hmm. I think I am wrong here :/.

**Comment by andrewrynhard** [comment]
If we don't inject it, should we? Feels like a dynamic enough thing.

**Comment by smira** [comment]
we never injected it automatically, even though we could

**Comment by andrewrynhard** [comment]
Would be nice if we would. Then users don't have to update environments if the change the api-endpoint flag
