### ISSUE TITLE
Need installer feedback

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/sidero#526]
Currently, if the Talos installer fails for any reason, that machine is wedged in a bad state in Sidero.  Sidero thinks Talos has been installed, but the machine won't boot.  It is, further, impossible to get any logs of this state if there is not any external collection of such.

We should have a Sidero API for installer progress reporting consisting of (at least) the following events:
 - Installer up and starting
 - Installer configuration acquired
 - Installation complete
 - Installation failure

This reporting mode could be enabled by kernel commandline flag... something like:`talos.installer.status.callback=https://sidero.mydomain.com`.  Because this occurs preinstallation, TLS auth will not be available.  Instead, we should report our UUID with each event.

**Comment by smira** [comment]
This was implemented via event parsing.
