### ISSUE TITLE
clusterctl 0.4.0 cannot bootstrap a management cluster

### ISSUE THREAD

**Issue by glitchcrab** [talos-systems/sidero#545]
When following the getting started doc, I ran `clusterctl init -b talos -c talos -i sidero` and the following error occurred:

```
Error: current version of clusterctl could install only v1alpha4 providers, detected v1alpha3 for provider bootstrap-talos`
```

I tried older versions of clusterctl, but they fail with different errors instead. Any suggestions as to how to resolve this would be most appreciated :)

**Comment by smira** [comment]
Sidero and Talos CAPI providers are not ready for CAPI 0.4.x yet.

clusterctl 0.3.22 should work fine though. Please make sure you're not using Kubernetes 1.22, as CAPI 0.3 supports only <= 1.21

**Comment by glitchcrab** [comment]
Ah ok thanks, this makes sense - apologies if I missed something in the docs which outlines this constraint.
