### ISSUE TITLE
Pre-acceptance, post register stage could cause some machines to drop into a UEFI select menu

### ISSUE THREAD

**Issue by frezbo** [talos-systems/sidero#558]
Environment:

RPi4 with UEFI firmware

Workflow:

Step 1: Rpi boots the sidero agent (sidero sends agent boot ipxe config)
Step 2: The Pi is registered as a server in sidero. Pi keeps on rebooting with the same ipxe config since the server is not yet accepted
Step 3: The server CR is accepted
Step 4: On the next Pi reboot cycle, the disk is wiped and Pi reboots and the disk is marked as clean in server CR
Step 5: This time the ipxe config sends a 404 since the server is accepted (not yet allocated) and the UEFI firmware drops into a menu selection screen

This would need a manual intervention of power cycling the Pi's once the server is allocated. The `SIDERO_CONTROLLER_MANAGER_BOOT_FROM_DISK_METHOD` option only sends the configured option parameter after the server has been allocated and talos has been installed.

The intermediate stage between a server acceptance and server allocation always seen to return a 404 for the ipxe config.

Should I open up a PR with a new config flag for sidero to control this behavior? Suggestions welcome

@andrewrynhard

**Comment by toboshii** [comment]
FYI, I'm running into this issue as well with some commodity HP machines without IPMI, where after acceptance but pre-binding they fall into a generic "No boot disk found" error screen that is inescapable without power cycling.

Continually looping is fine with me as well (and honestly what I expected the default behavior to be without IPMI). Look forward to seeing this as an option :+1:
