### ISSUE TITLE
Cluster deletion hangs

### ISSUE THREAD

**Issue by smira** [talos-systems/sidero#69]
Attempt to `kubectl delete cluster xyz` hangs at least when cluster is not fully provisioned yet, no way to clean up after failed cluster install.

**Comment by rsmitty** [comment]
Related to #57. We'll keep this one and close the other.

**Comment by rsmitty** [comment]
Looks like, at least for last night's conformance, this was the reason for our failure. Suspect this may actually be in the control plane provider instead of Sidero. Assigning to myself to take care of these. 

Related to https://github.com/talos-systems/talos/issues/2529

**Comment by rsmitty** [comment]
Should be closed by https://github.com/talos-systems/cluster-api-control-plane-provider-talos/pull/11but we'll want to validate
