### ISSUE TITLE
Cannot use sidero infrastructure provider with 1.0.2 clusterctl

### ISSUE THREAD

**Issue by waseem-h** [talos-systems/sidero#698]
I can't seem to use clusterctl v1.0.2 with the latest sidero release. Any plans on supporting the latest version soon?

Here is my output:

```
clusterctl init -b talos -c talos -i sidero
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider infrastructure-sidero

clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.2", GitCommit:"89db44e9a462028267ed49295359fe9db2a6a10a", GitTreeState:"clean", BuildDate:"2021-12-06T17:52:47Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rsmitty** [comment]
Hey @waseem-h, thx for the report. This is a known issue and we should be cutting a new GA release next week. In the meantime, you should be able to try the alpha release if you want. Something like `clusterctl init -b talos -c talos -i sidero:v0.5.0-alpha.0` to force that installation.

**Comment by waseem-h** [comment]
Thanks for the info @rsmitty . I just tried to use the latest version but still getting the same error:
```
clusterctl init -b talos -c talos -i sidero:v0.5.0-alpha.0
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider infrastructure-sidero
```

Are you sure that 0.5.0-alpha.0 is v1beta1 provider?

**Comment by rsmitty** [comment]
well, I *thought* so. maybe we're just not quite there on the uplift yet, but the v0.5.x series should be v1beta1 support if I'm not mistaken. let me see where we are on getting things uplifted early next week. I'll ping you when I have a good answer.
